image: registry.gitlab.com/safesurfer/safesurfer-desktop

include:
  template: Dependency-Scanning.gitlab-ci.yml

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    # make built directory
    - mkdir builtBinaries
    # prep project dependencies
    - npm i
    # download appimage dependencies
    - make prep-appimage
  script:
    # build AppImage
    - make build-appimage || true
    - cd tools
    - ./appimagetool-x86_64.AppImage --appimage-extract || true
    - ./squashfs-root/AppRun -n -s ../nz.co.safesurfer.SafeSurfer-Desktop.AppDir
    - mv Safe_Surfer-x86_64.AppImage ../builtBinaries/.
    - cd ..
    # clean build
    - make clean

    # build Linux binary zip
    - make build-linuxzip
    - mv SafeSurfer-Desktop-Linux.zip builtBinaries/.
    # clean build
    - make clean

    # build macOS & zip it
    - node_modules/.bin/electron-builder --mac zip
    - mv dist/SafeSurfer-Desktop-*-mac.zip builtBinaries/.
    # clean build
    - make clean

    # build windows (64-bit)
    - export LANG=
    - make build-windows
    - mv dist/SafeSurfer-Desktop\ *.exe builtBinaries/.
    # clean build
    - make clean

    # update names of binaries
    - support/renameBinaries.sh builtBinaries/Safe_Surfer-x86_64.AppImage
    - support/renameBinaries.sh builtBinaries/SafeSurfer-Desktop-Linux.zip
    - support/renameBinaries.sh builtBinaries/SafeSurfer-Desktop-*-mac.zip
    - support/renameBinaries.sh builtBinaries/SafeSurfer-Desktop\ *.exe

    # hash all binaries
    - cd builtBinaries && sha256sum * > sha256ums.txt && cd ..
  artifacts:
    expire_in: 5 days
    paths:
      - builtBinaries/*

deploy:
  stage: deploy
  script:
    - mkdir .public
    - cp -r builtBinaries/* .public
    - mv .public public
  dependencies:
    - build
  artifacts:
    paths:
      - public/*
  only:
    - tags