image: ubuntu

stages:
  - build
  - deploy

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r builtBinaries/* .public
    - mv .public public
  dependencies:
    - build
  artifacts:
    paths:
      - public/*
  only:
    - tags
    - master

build:
  stage: build
  before_script:
    - echo "Pacific/Auckland" > /etc/timezone
    - apt update
    - apt upgrade -y
    # install deps for build enviroment
    - DEBIAN_FRONTEND=noninteractive apt install -yq nodejs npm tar bzip2 wget fuse wine-stable unzip zip mono-devel curl libfuse2 binutils bash-completion fakeroot html2text libmd0 build-essential rpm2cpio cpio
    - dpkg --add-architecture i386 && apt update && apt install -y wine32
    # make built directory
    - mkdir builtBinaries
    # prep dependencies
    - npm i
  script:
    # build AppImage
    - make prep-appimage
    - make build-appimage || true
    - cd tools
    - ./appimagetool-x86_64.AppImage --appimage-extract || true
    - ./squashfs-root/AppRun -n -s ../nz.co.safesurfer.SafeSurfer-Desktop.AppDir
    - mv Safe_Surfer-x86_64.AppImage ../builtBinaries/.
    - cd ..
    # clean build
    - make clean
    # build macOS & zip it
    - node_modules/.bin/electron-builder --mac zip
    - mv dist/SafeSurfer-Desktop-*-mac.zip builtBinaries/.
    # clean build
    - make clean
    # build windows (64-bit)
    - export LANG=
    - make build-windows
    - mv dist/SafeSurfer-Desktop\ *.exe builtBinaries/.
    # clean build
    - make clean
    # hash all binaries
    - cd builtBinaries && sha256sum * > sha256ums.txt && cd ..
  artifacts:
    expire_in: 5 days
    paths:
      - builtBinaries/*
  only:
    - tags
    - master