image: opensuse/leap

stages:
  - tests
  - build
  - deploy

tests:
  stage: tests
  script:
    # make built directory
    - mkdir builtBinaries
    # install required packages
    - zypper in -y git nodejs npm8 tar bzip2 wget fuse AppStream appstream-glib unzip zip curl libfuse2-32bit binutils
    # prep dependencies
    - npm i
    # verify appstream data
    - appstream-util validate support/linux/shared-resources/SafeSurfer-Desktop.appdata.xml
    # setup env
    - export DISPLAY=:1
    # run electron tests on app
    - npm test

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r builtBinaries/* .public
    - mv .public public
  dependencies:
    - build
  artifacts:
    paths:
      - public/*
  only:
    - tags
    - master

build:
  stage: build
  before_script:
    # install deps for build enviroment
    - zypper in -y git nodejs npm8 tar bzip2 wget fuse AppStream wine unzip zip mono-devel curl libfuse2-32bit binutils
    - zypper in -y -t pattern devel_basis
  script:
    # make built directory
    - mkdir builtBinaries
    # prep dependencies
    - npm i
    # build AppImage
    - make BUILDMODE="RELEASE" configure
    - make prep-appimage BUILDMODE="RELEASE" build-appimage || true
    - cd tools
    - ./appimagetool-x86_64.AppImage --appimage-extract || true
    - ./squashfs-root/AppRun -n -s ../nz.co.safesurfer.SafeSurfer-Desktop.AppDir
    - mv Safe_Surfer-x86_64.AppImage ../builtBinaries/.
    - cd ..
    # clean build
    - make clean
    # build macOS & zip it
    - make BUILDMODE="RELEASE" configure
    - make build-macos
    - cd release-builds/SafeSurfer-Desktop-darwin-x64
    - zip -q -r SafeSurfer-Desktop-x64.app.zip SafeSurfer-Desktop.app
    - cd ../..
    - mv release-builds/SafeSurfer-Desktop-darwin-x64/SafeSurfer-Desktop-x64.app.zip builtBinaries/.
    # clean build
    - make clean
    # build windows (64-bit)
    - make BUILDMODE="RELEASE" configure
    - make build-windows
    - make compile-win-setup
    - mv release-builds/SafeSurfer-Desktop-x64.exe builtBinaries/.
    # clean build
    - make clean
    # build windows (32-bit)
    - make BUILDMODE="RELEASE" configure
    - make build-windows32
    - make compile-win-setup32
    - mv release-builds/SafeSurfer-Desktop-ia32.exe builtBinaries/.
    # hash all binaries
    - cd builtBinaries && sha256sum * > sha256ums.txt && cd ..
  dependencies:
    - tests
  artifacts:
    expire_in: 5 days
    paths:
      - builtBinaries/*
  only:
    - tags
    - master