#!/bin/bash
set -e

VENDORPREFIX=appimagekit

THIS="$0"

find-up () {
  path="$(dirname "$(readlink -f "${THIS}")")"
  while [[ "$path" != "" && ! -e "$path/$1" ]]; do
    path=${path%/*}
  done
}

if [ -z $APPDIR ] ; then
  APPDIR=$(find-up "AppRun")
fi

export PATH="${APPDIR}/usr/bin:${PATH}"
DESKTOP_FILE="$APPDIR/nz.co.safesurfer.SafeSurferDesktop.desktop"
BIN="$APPDIR/opt/SafeSurfer-Desktop/SafeSurfer-Desktop"

atexit() {
if [ -z "$APPIMAGE_EXIT_AFTER_INSTALL" ] ; then
  if [[ $NUMBER_OF_ARGS -eq 0 ]] ; then
    exec "$BIN"
  else
    exec "$BIN" "${args[@]}"
  fi
fi
}

if [ ! -f "$DESKTOP_FILE" ] ; then
  echo "Desktop file is missing. Please run ${THIS} from within an AppImage."
  exit 0
fi

trap atexit EXIT