#!/bin/bash
set -e

find-up () {
  path="$(dirname "$(readlink -f "${THIS}")")"
  while [[ "$path" != "" && ! -e "$path/$1" ]]; do
    path=${path%/*}
  done
  # echo "$path"
}

if [ -z $APPDIR ] ; then
  APPDIR=$(find-up "AppRun")
fi

exec "$APPDIR"/opt/SafeSurfer-Desktop/SafeSurfer-Desktop