name: safesurfer-desktop
version: 1.0.0rc4
summary: Keep safe in the digitial surf with Safe Surfer.
description: >
  Safe Surfer Desktop is an Electron based app, which sets the Safe Surfer DNS settings for you (on a device, not network).

grade: stable
confinement: classic

parts:
  safesurferdesktop:
    plugin: dump
    source: http://142.93.48.189/files/desktop/9-$SNAPCRAFT_PROJECT_VERSION/SafeSurfer-Desktop-$SNAPCRAFT_PROJECT_VERSION-9-linux.zip
    after:
      - desktop-gtk3
    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6

  curl:
    plugin: autotools
    source-type: tar
    source: https://github.com/curl/curl/releases/download/curl-7_62_0/curl-7.62.0.tar.xz
    build-packages:
      - g++
      - gcc
      - make

apps:
  safesurferdesktop:
    command: usr/bin/sscli launch