name: safesurfer-desktop
version: 1.0.0rc3
type: app
summary: Keep safe in the digitial surf with Safe Surfer.
description: >
  Safe Surfer Desktop is an Electron based app, which sets the Safe Surfer DNS settings for you (on a device, not network).

confinement: classic

parts:
  safesurfer-desktop:
    plugin: make
    source: ../../../
    prepare: |
     npm i
     make BUILDMODE=RELEASE UPDATES=false configure
    build: |
     make build-linux
    build-packages:
     - nodejs
     - npm
     - unzip
    install: |
     make DESTDIR=$SNAPCRAFT_PART_INSTALL install
    prime:
      - -node_modules

    stage-packages:
      - libnotify4
      - libappindicator1
      - libxtst6
      - libnss3
      - libxss1
      - fontconfig-config
      - gconf2
      - libasound2
      - pulseaudio

apps:
  safesurfer-desktop:
    command: desktop-launch /usr/lib64/SafeSurfer-Desktop/SafeSurfer-Desktop
    plugs:
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl

  sscli:
    command: sscli