#!/bin/bash

# SafeSurfer-Desktop - AppRun

#
# Copyright (C) 2018 Caleb Woodbine <info@safesurfer.co.nz>
#
# This file is part of SafeSurfer-Desktop.
#
# SafeSurfer-Desktop is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SafeSurfer-Desktop is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with SafeSurfer-Desktop.  If not, see <https://www.gnu.org/licenses/>.
#

set -e

AppVersion="1.0.0"
AppBuild=10

if [ ! -z "$DEBUG" ]
then
	env
	set -x
fi

if [ ! -z "$VERBOSE" ]
then
	env
	set -v
fi

args="$1"
VENDORPREFIX=appimagekit

THIS="$0"

function dirResolve() {
# resolve a directory
path="$(dirname "$(readlink -f "${THIS}")")"
while [[ "$path" != "" && ! -e "$path/$1" ]]
do
	path=${path%/*}
done
}

if [ -z "$APPDIR" ]
then
	APPDIR=$(dirResolve "AppRun")
fi

export PATH="${APPDIR}/usr/bin:${PATH}"
export LD_LIBRARY_PATH="${APPDIR}/usr/lib":$LD_LIBRARY_PATH
export LD_LIBRARY_PATH="${APPDIR}/usr/lib64":$LD_LIBRARY_PATH
export APPIMAGE_LIBRARY_PATH="${APPIMAGE_LIBRARY_PATH}:/usr/lib"
export APPIMAGE_LIBRARY_PATH="${APPIMAGE_LIBRARY_PATH}:/usr/lib64"
DESKTOP_FILE="$APPDIR/nz.co.safesurfer.SafeSurfer-Desktop.desktop"
BIN="$APPDIR/usr/lib64/SafeSurfer-Desktop/SafeSurfer-Desktop"

if [[ ! -x "$(which curl)" ]] && [[ ! -x "$(which wget)" ]]
then
	export PATH="${APPDIR}/usr/local/bin/curl:${PATH}"
fi

if [[ ! -x "$(which zenity)" ]] && [[ ! -x "$(which kdialog)" ]] && [[ ! -x "$(which Xdialog)" ]]
then
	export PATH="${APPDIR}/usr/local/bin/zenity:${PATH}"
fi

function atexit() {
# execute on trap
if [ -z "$APPIMAGE_EXIT_AFTER_INSTALL" ]
then
	if [[ -f "${APPDIR}/ENABLEUPDATES" ]]
	then
		SAFESURFER_APPUPDATES="true" SSCLILOCATION="$APPIMAGE " LINUXPACKAGEFORMAT="appimage" exec "$BIN"
	else
		SSCLILOCATION="$APPIMAGE " LINUXPACKAGEFORMAT="appimage" exec "$BIN"
	fi
fi
}

function errorMsg() {
# display an error
if [ -x /usr/bin/zenity ]
then
	LD_LIBRARY_PATH="" zenity --error --text "${1}" 2>/dev/null
elif [ -x /usr/bin/kdialog ]
then
	LD_LIBRARY_PATH="" kdialog --msgbox "${1}" 2>/dev/null
elif [ -x /usr/bin/Xdialog ]
then
	LD_LIBRARY_PATH="" Xdialog --msgbox "${1}" 2>/dev/null
else
	echo "${1}"
fi
exit 1
}

function yesnoPrompt() {
# display a yes or no prompt
TITLE="$1"
TEXT="$2"
if [ -x /usr/bin/zenity ]
then
	LD_LIBRARY_PATH="" zenity --question --title="$TITLE" --text="$TEXT" --height=250 --width=400 --window-icon="${APPDIR}/ss-logo.png" 2>/dev/null || exit 0
elif [ -x /usr/bin/kdialog ]
then
	LD_LIBRARY_PATH="" kdialog --title "$TITLE" --yesno "$TEXT" || exit 0
elif [ -x /usr/bin/Xdialog ]
then
	LD_LIBRARY_PATH="" Xdialog --title "$TITLE" --clear --yesno "$TEXT" 10 80 || exit 0
else
	echo "zenity, kdialog, Xdialog missing. Skipping ${THIS}."
	exit 0
fi
}

function infoMsg() {
# display a yes or no prompt
TITLE="$1"
TEXT="$2"
if [ -x /usr/bin/zenity ]
then
	LD_LIBRARY_PATH="" zenity --info --title="$TITLE" --text="$TEXT" --height=250 --width=400 --window-icon="${APPDIR}/ss-logo.png" 2>/dev/null || exit 0
elif [ -x /usr/bin/kdialog ]
then
	LD_LIBRARY_PATH="" kdialog --title "$TITLE" --info "$TEXT" || exit 0
elif [ -x /usr/bin/Xdialog ]
then
	LD_LIBRARY_PATH="" Xdialog --title "$TITLE" --clear --info "$TEXT" 10 80 || exit 0
else
	echo "zenity, kdialog, Xdialog missing. Skipping ${THIS}."
	exit 0
fi
}

function cliOrGUIinfoMsg() {
# display a message whether user is running app from cli or GUI
TITLE="$1"
MSG="$2"
if ! tty -s
then
	infoMsg "$TITLE" "$MSG"
else
  	echo "$TITLE: $MSG"
fi
}

function check_prevent() {
FILE=$1
if [ -e "$FILE" ]
then
	exit 0
fi
}

function uninstall_icons() {
# uninstall previous icons
for size in 16 24 32 48 64 128 256 512 1024
do
	xdg-icon-resource uninstall --noupdate --size "$size" "$VENDORPREFIX-SafeSurfer-Desktop"
done
}

function check_dep() {
# check if a given dependency is present
DEP="$1"
MSG="$2"
if [ -z "$(which $DEP)" ]
then
	if ! tty -s && [ ! -z "$DISPLAY_A_MSG" ]
	then
		infoMsg "Safe Surfer desktop: Dependencies" "It appears that '$DEP' is missing. $MSG"
	fi
  	echo "[!] $DEP is missing. $MSG"
  	return 1
else
	echo "[*] $DEP is present."
	return 0
fi
}

function rm_sscli() {
# rm sscli which is in /tmp
rm -f /tmp/sscli-appimage
}

if [[ "$(whoami)" = root ]] && [[ $# = 0 ]]
then
	cliOrGUIinfoMsg "ERROR" "You should not run Safe Surfer desktop as root."
	exit 1
fi

check_dep curl || ( DISPLAY_A_MSG=0 check_dep wget "Since your system doesn't have cURL or wget, the app cannot be used. Please install cURL or wget via your software repositories.." || exit 1 )

case "$args" in
	--remove-integration|-r)
		# remove desktop integration
		set -e
		uninstall_icons
		if [[ $EUID -ne 0 ]]
		then
			rm -f "$HOME/.local/share/applications/$VENDORPREFIX-nz.co.safesurfer.SafeSurfer-Desktop.desktop"
		else
			rm -f "/usr/local/share/applications/$VENDORPREFIX-nz.co.safesurfer.SafeSurfer-Desktop.desktop"
		fi
		xdg-desktop-menu forceupdate
		# for MIME
		gtk-update-icon-cache

		echo "Integration was successfully removed."
		exit
		;;
	sscli)
		shift
		trap rm_sscli EXIT
		cp "${APPDIR}"/usr/bin/sscli /tmp/sscli-appimage || (echo "ERROR: Unable to copy sscli to /tmp" && exit 1)
		ISAPPIMAGE=0 APPRUN=${0} /tmp/sscli-appimage "$1"
		exit
		;;
	curl)
		shift
		exec "${APPDIR}"/usr/local/bin/curl/curl $@
		exit $?
		;;
	zenity)
		shift
		exec "${APPDIR}"/usr/local/bin/zenity/zenity $@
		exit $?
		;;
	help|--help|-h)
		echo "SafeSurfer-Desktop (AppImage) help menu"
		echo "---------------------------------------"
		echo
		echo "--remove-integration|-r	to remove desktop integration."
		echo "sscli			to use the sscli utility."
		exit
		;;
esac

trap atexit EXIT

DISPLAY_A_MSG=0 check_dep pkexec "Without pkexec/polkit, SafeSurfer-desktop is unable to enable DNS settings. Please install polkit-1 from via software repositories."

if [[ -e "${APPDIR}/NOINTEGRATION" ]]
then
	exit
fi

# Exit immediately of one of these files is present
# (e.g., because the desktop environment wants to handle desktop integration itself)
check_prevent "$HOME/.local/share/$VENDORPREFIX/no_desktopintegration"
check_prevent "/usr/share/$VENDORPREFIX/no_desktopintegration"
check_prevent "/etc/$VENDORPREFIX/no_desktopintegration"

if [ -f "/usr/local/share/applications/$VENDORPREFIX-SafeSurfer-Desktop" ]
then
	echo "<-> App appears to have it's desktop file installed in a system directory."
	exit 0
fi

# Exit immediately if appimaged is running
pidof appimaged 2>/dev/null && exit 0

# Exit immediately if $DESKTOPINTEGRATION is not empty
if [ ! -z "$DESKTOPINTEGRATION" ]
then
	exit 0
fi

# Check whether dependencies are present in base system (we do not bundle these)
# http://cgit.freedesktop.org/xdg/desktop-file-utils/
DISPLAY_A_MSG=0 check_dep desktop-file-install
DISPLAY_A_MSG=0 check_dep xdg-icon-resource
DISPLAY_A_MSG=0 check_dep xdg-mime
DISPLAY_A_MSG=0 check_dep xdg-desktop-menu

if [ ! -f "$DESKTOP_FILE" ]
then
	echo "Desktop file is missing. Please run ${THIS} from within an AppImage."
	exit 0
fi

if [ -z "$APPIMAGE" ]
then
	APPIMAGE="$APPDIR/AppRun"
	# Not running from within an AppImage; hence using the AppRun for Exec=
fi

# Determine where the desktop file should be installed
if [[ $EUID -ne 0 ]]
then
	DESTINATION_DIR_DESKTOP="$HOME/.local/share/applications"
	SYSTEM_WIDE=""
else
	DESTINATION_DIR_DESKTOP="/usr/local/share/applications"
	# for xdg-mime and xdg-icon-resource
	SYSTEM_WIDE="--mode system"
fi

# Check if the desktop file is already there
# and if so, whether it points to the same AppImage
if [ -e "$DESTINATION_DIR_DESKTOP/$VENDORPREFIX-nz.co.safesurfer.SafeSurfer-Desktop.desktop" ] && [ -z "$APPIMAGE_NO_UPGRADE" ]
then
	#INSTALLED_APP_VERSION=$(grep "^X-AppImage-BuildId=" "$DESTINATION_DIR_DESKTOP/$VENDORPREFIX-nz.co.safesurfer.SafeSurfer-Desktop.desktop" | head -n 1 | cut -d " " -f 1)
	#APP_VERSION=$(grep "^X-AppImage-BuildId=" "$DESKTOP_FILE" | head -n 1 | cut -d " " -f 1)
	InstalledAppBuild=$(grep "X-AppImage-Build=" "$DESTINATION_DIR_DESKTOP/$VENDORPREFIX-nz.co.safesurfer.SafeSurfer-Desktop.desktop" | cut -d '=' -f2)
	InstalledAppVersion=$(grep "X-AppImage-Version=" "$DESTINATION_DIR_DESKTOP/$VENDORPREFIX-nz.co.safesurfer.SafeSurfer-Desktop.desktop" | cut -d '=' -f2)
	echo
	echo "[Version # installed] : $InstalledAppVersion"
	echo "[Build   # installed] : $InstalledAppBuild"
	if [ "$InstalledAppBuild" = "$AppBuild" ]
	then
		exit 0
	else
		if [ -z "$APPIMAGE_SILENT_INSTALL" ]
		then
			yesnoPrompt "Upgrade" "You've launched a version ($AppVersion) which is not what is installed ($InstalledAppVersion) of SafeSurfer-Desktop.\\nWould you like to update the integration?"
			APPIMAGE_UPGRADE=true
		fi
		uninstall_icons
		rm -f "$HOME/.local/share/applications/$VENDORPREFIX-nz.co.safesurfer.SafeSurfer-Desktop.desktop"
	fi
fi

# we ask the user only if we have found no reason to skip until here
if [ -z "$APPIMAGE_SILENT_INSTALL" ] && [ ! "$APPIMAGE_UPGRADE" = true ]
then
	yesnoPrompt "Install" "Would you like to integrate $APPIMAGE with your system?\\n\\nThis will add it to your applications menu and install icons.\\nIf you don't do this you can still launch the application by double-clicking on the AppImage.\\n\\nPlease note you can remove integration by running '$APPIMAGE --remove-integration'"
fi

desktop-file-install --rebuild-mime-info-cache \
	--vendor=$VENDORPREFIX --set-key=Exec --set-value="\"${APPIMAGE}\" %U" \
	--set-key=X-AppImage-Comment --set-value="Generated by ${THIS}" \
	--set-key=X-AppImage-Version --set-value="$AppVersion" \
	--set-key=X-AppImage-Build --set-value="$AppBuild" \
	--set-icon="ss-logo" --set-key=TryExec --set-value="${APPIMAGE// /\\s}" "$DESKTOP_FILE" \
	--dir "$DESTINATION_DIR_DESKTOP" \
	--mode=755

sed -i -e "s,APPIMAGEFILE,$APPIMAGE,g" "$DESTINATION_DIR_DESKTOP/$VENDORPREFIX-$(basename $DESKTOP_FILE)"

uninstall_icons

echo "STATUS: Installing icons to user's home directory."

# Install the icon files for the application
for size in 16 24 32 48 64 128 256 512 1024
do
	xdg-icon-resource install --noupdate --context apps --size "$size" "$APPDIR/usr/share/icons/hicolor/${size}x${size}/apps/ss-logo.png" "$VENDORPREFIX-SafeSurfer-Desktop"
done

# force update the icon cache
xdg-icon-resource forceupdate

# Install the icon files for the mime type;
ICONS=$(find "${APPDIR}/usr/share/icons/" -wholename "*/*/*.png" 2>/dev/null || true)
for ICON in $ICONS
do
	ICON_SIZE=$(echo "${ICON}" | rev | cut -d "/" -f 3 | rev | cut -d "x" -f 1)
	xdg-icon-resource install --context mimetypes --size "${ICON_SIZE}" "${ICON}" $(basename "$ICON" | sed -e 's/.png//g')
done

xdg-desktop-menu forceupdate
# for MIME
gtk-update-icon-cache

echo "STATUS: Done, now launching app..."